[UKI]
Linux = /boot/vmlinuz-forge
Initrd = /boot/initramfs-forge.img
Cmdline = @/etc/kernel/cmdline
  lockdown=integrity module.sig_enforce=1 dm-verity
SecureBootPrivateKey = /etc/secureboot/db.key
SecureBootCertificate = /etc/secureboot/db.crt

[PCRSignature:NAME]
Phases = enter-initrd:leave-initrd:sysinit:ready:shutdown:final
